#!/bin/bash
DELAY=1
configuredClient=""
currentVersion="1.0"

checkOpenSSL()
{
  if  ! command -v openssl &>/dev/null; then
    echo "Error: to use this tool openssl must be installed. Add with apt instal lopenssl" >&2
    return 1
  else
    return 0
  fi
}

## This function determines which http get tool the system has installed and returns an error if there isnt one
getConfiguredClient()
{
  if  command -v curl &>/dev/null; then
    configuredClient="curl"
  elif command -v wget &>/dev/null; then
    configuredClient="wget"
  elif command -v http &>/dev/null; then
    configuredClient="httpie"
  elif command -v fetch &>/dev/null; then
    configuredClient="fetch"
  else
    echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
    return 1
  fi
}

## Allows to call the users configured client without if statements everywhere
httpGet()
{
  case "$configuredClient" in
    curl)  curl -A curl -s "$@" ;;
    wget)  wget -qO- "$@" ;;
    httpie) http -b GET "$@" ;;
    fetch) fetch -q "$@" ;;
  esac
}

usage()
{
  cat <<EOF
Siteciphers
Description: Checks the available ciphers for the SSL of an https site.
Usage: siteciphers [flag] or siteciphers [optionalDFlag] [website]
  -u  Update Bash-Snippet Tools
  -h  Show the help
  -v  Get the tool version
  -d  Set the delay between requests sent to the site (default is 1 sec)
Examples:
  siteciphers hedgehogsecurity.co.uk
  siteciphers -d 0.5 hedgehogsecurity.co.uk
EOF
}

checkInternet()
{
  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
}

checkCiphers()
{
  ciphers=$(openssl ciphers 'ALL:eNULL' | sed -e 's/:/ /g') # grab all ciphers
  SERVER=$1:443 # setup the connection server
  for cipher in ${ciphers[*]}; do # for all possible ciphers
    result=$(echo | openssl s_client -cipher "$cipher" -connect $SERVER 2>&1)
    if [[ "$result" =~ ":error:" ]]; then
      if [[ -z $2 ]]; then
        error=$(echo -n $result | cut -d':' -f6)
        echo "$cipher - NO ($error)"
      fi
    else
      if [[ "$result" =~ "Cipher is $cipher" || "$result" =~ "Cipher    :" ]]; then
        echo "$cipher - YES"
      else
        if [[ -z $2 ]]; then
          echo "$cipher - UNKNOWN RESPONSE - $result"
        fi
      fi
    fi
    sleep $DELAY # sleep as to not overload the requests to the server
  done
}

checkOpenSSL || exit 1
getConfiguredClient || exit 1


if [[ $# == "0" ]]; then
  usage
  exit 1
elif [[ $1 == "help" ]]; then
  usage
  exit 0
fi

while getopts "huvd:" opt; do ## alows for using options in bash
  case "$opt" in
    \?) echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    d)  #set the delay with the -d option
        DELAY=$OPTARG
        dFlag="1"
        ;;
    u)  checkInternet || exit 1
        update
        exit 0
        ;;
    h)  usage
        exit 0
        ;;
    v)  echo "Version $currentVersion"
        exit 0
        ;;
    :)  ## will run when no arguments are provided to to d options
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
  esac
done

checkInternet || exit 1
if [[ $dFlag == "1" ]]; then
  checkCiphers $3 || exit 1 # if dflag is present input will look like siteciphers -d 0.5 github.com making the website the third arg
else
  checkCiphers $1 || exit 1
fi
